version: '2'

services:

### MySQL Container #########################################

    mysql:
            build: ./docker/mysql
            volumes:
                - mysql:/var/lib/mysql
            ports:
                - "3306:3306"
            environment:
                MYSQL_DATABASE: homestead
                MYSQL_USER: homestead
                MYSQL_PASSWORD: secret
                MYSQL_ROOT_PASSWORD: root

volumes:
    mysql:
        driver: "local"