<?php

namespace App\Transformers;

use App\ImageForm;
use League\Fractal\TransformerAbstract;

class ImageFormTransformer extends TransformerAbstract 
{
	public function transform(ImageForm $if)
	{
		return [
			'avc_h' => $if->avc_h,
			'avc_intra' => $if->avc_intra,
			'hs' => $if->hs,
			'topolobar' => $if->topolobar,
			'topoprofunda' => $if->topoprofunda,
			'volhematoma' => $if->volhematoma,
			'iv' => $if->iv,
			'fisher' => $if->fisher,
			'hidrocefalia' => $if->hidrocefalia,
			'angiotomografia' => $if->angiotomografia,
			'aneurisma' => $if->aneurisma,
			'angiornm' => $if->angiornm,
			'aneurismarnm' => $if->aneurismarnm,
			'dsa' => $if->dsa,
			'aneurismadsa' => $if->aneurismadsa,
			'ic' => $if->ic,
			'avc_i' => $if->avc_i,
			'avc_tc' => $if->avc_tc,
			'avc_rnm' => $if->avc_rnm,
			'efeitotumofativo' => $if->efeitotumofativo,
			'avc_th' => $if->avc_th,
			'rnm_thop' => $if->rnm_thop,
			'fa_aspects' => $if->fa_aspects,
			'fa_lado' => $if->fa_lado,
			'fa_topografia' => $if->fa_topografia,
			'fa_tvc' => $if->fa_tvc,
			'tvc_op' => $if->tvc_op,
			'fa_tumefativo' => $if->fa_tumefativo,
			'fa_detec' => $if->fa_detec,
			'fa_dwi' => $if->fa_dwi,
			'fa_lado_rnm' => $if->fa_lado_rnm,
			'fa_topornm' => $if->fa_topornm,
			'fa_tvcrnm' => $if->fa_tvcrnm,
			'fa_atc' => $if->fa_atc,
			'rnm_tvc' => $if->rnm_tvc,
			'rnm_avcidetec' => $if->rnm_avcidetec,
			'rnm_rdwi' => $if->rnm_rdwi,
			'rnm_lado' => $if->rnm_lado,
			'rnm_topografia' => $if->rnm_topografia,
			'rnm_tvc_op' => $if->rnm_tvc_op,
			'rnm_tumefativo' => $if->rnm_tumefativo,
			'rnm_selec' => $if->rnm_selec,
			'rnm_dal' => $if->rnm_dal,
			'rnm_cd' => $if->rnm_cd,
			'rnm_et'=> $if->rnm_et,
			'rnm_thop' => $if->rnm_thop,
			'tvc_oprnm' => $if->tvc_oprnm,
			'et_rnm' => $if->et_rnm,
			'atc_opga' => $if->atc_opga,
			'arnm_opga' => $if->arnm_opga,
			'avc_rnm_th' => $if->avc_rnm_th,
			'rnm_opga' => $if->rnm_opga,
			'atc_entrenose' => $if->atc_entrenose,
			'fa_atcextra' => $if->fa_atcextra,
			'rnm_normal' => $if->rnm_normal,
			'rnm_acd' => $if->rnm_acd,
			'rnm_ace' => $if->rnm_ace,
			'rnm_avd' => $if->rnm_avd,
			'rnm_ave' => $if->rnm_ave,
			'rnm_acdlado' => $if->rnm_acdlado,
			'rnm_acdloc' => $if->rnm_acdloc,
			'rnm_acdestlado' => $if->rnm_acdestlado,
			'rnm_acdestloc' => $if->rnm_acdestloc,
			'rnm_acelado' => $if->rnm_acelado,
			'rnm_aceloc' => $if->rnm_aceloc,
			'rnm_aceestlado' => $if->rnm_aceestlado,
			'rnm_aceestloc' => $if->rnm_aceestloc,
			'rnm_avdlado' => $if->rnm_avdlado,
			'rnm_avdloc' => $if->rnm_avdloc,
			'rnm_avdestlado' => $if->rnm_avdestlado,
			'rnm_avdestloc' => $if->rnm_avdestloc,
			'rnm_avelado' => $if->rnm_avelado,
			'rnm_aveloc' => $if->rnm_aveloc,
			'rnm_aveestlado' => $if->rnm_aveestlado,
			'rnm_aveestloc' => $if->rnm_aveestloc,
			'rnm_acdestgrau' => $if->rnm_acdestgrau,
			'rnm_aceestgrau' => $if->rnm_aceestgrau,
			'rnm_avdestgrau' => $if->rnm_avdestgrau,
			'rnm_aveestgrau' => $if->rnm_aveestgrau,
			'arnm_estopga' => $if->arnm_estopga,
			'fa_rnmextra' => $if->fa_rnmextra,
			'arnm_normal' => $if->arnm_normal,
			'arnm_acdlado' => $if->arnm_acdlado,
			'arnm_acdloc' => $if->arnm_acdloc,
			'arnm_acdestlado' => $if->arnm_acdestlado,
			'arnm_acdestloc' => $if->arnm_acdestloc,
			'arnm_acdestgrau' => $if->arnm_acdestgrau,
			'arnm_ace' => $if->arnm_ace,
			'arnm_acelado' => $if->arnm_acelado,
			'arnm_aceloc' => $if->arnm_aceloc,
			'arnm_aceestlado' => $if->arnm_aceestlado,
			'arnm_aceestloc' => $if->arnm_aceestloc,
			'arnm_aceestgrau' => $if->arnm_aceestgrau,
			'arnm_avd' => $if->arnm_avd,
			'arnm_avdlado' => $if->arnm_avdlado,
			'arnm_avdloc' => $if->arnm_avdloc,
			'arnm_avdestlado' => $if->arnm_avdestlado,
			'arnm_avdestloc' => $if->arnm_avdestloc,
			'arnm_avdestgrau' => $if->arnm_avdestgrau,
			'arnm_ave' => $if->arnm_ave,
			'arnm_avelado' => $if->arnm_avelado,
			'arnm_aveloc' => $if->arnm_aveloc,
			'arnm_aveestlado' => $if->arnm_aveestlado,
			'arnm_aveestloc' => $if->arnm_aveestloc,
			'arnm_aveestgrau' => $if->arnm_aveestgrau,
			'arnm_acd' => $if->arnm_acd,
			'dsanote' => $if->dsanote,
			'dsanew' => $if->dsanew,
			'css1' => $if->css1 ?? [],
			'css2' => $if->css2 ?? [],
			'css3' => $if->css3 ?? [],
			'uploadimg' => $if->uploadimg,
		];
	}
}


